// <auto-generated />
using System;
using Libary_asm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Libary_asm.Migrations
{
    [DbContext(typeof(LibaryContext))]
    [Migration("20210414083725_CreateDatabase8")]
    partial class CreateDatabase8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Libary_asm.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Son tung m-tp 1",
                            CategoryId = 1,
                            Name = "MCK o Circle K1 "
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Son tung m-tp 2",
                            CategoryId = 1,
                            Name = "MCK o Circle K2"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Son tung m-tp 3",
                            CategoryId = 1,
                            Name = "MCK o Circle K3"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Son tung m-tp 4",
                            CategoryId = 1,
                            Name = "MCK o Circle K4"
                        });
                });

            modelBuilder.Entity("Libary_asm.Models.BorrowDetail", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BorrowRequestId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "BorrowRequestId");

                    b.HasIndex("BorrowRequestId");

                    b.ToTable("BorrowDetails");
                });

            modelBuilder.Entity("Libary_asm.Models.BorrowRequest", b =>
                {
                    b.Property<int>("BorrowRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BorrowRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowRequests");
                });

            modelBuilder.Entity("Libary_asm.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Test2"
                        });
                });

            modelBuilder.Entity("Libary_asm.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BorrowRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("BorrowRequestId1")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("BorrowRequestId1");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BorrowRequestId = 0,
                            Password = "123",
                            RememberMe = false,
                            Role = 0,
                            Username = "chinhtkt"
                        });
                });

            modelBuilder.Entity("Libary_asm.Models.Book", b =>
                {
                    b.HasOne("Libary_asm.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Libary_asm.Models.BorrowDetail", b =>
                {
                    b.HasOne("Libary_asm.Models.Book", "Book")
                        .WithMany("BorrowDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Libary_asm.Models.BorrowRequest", "BorrowRequest")
                        .WithMany("BorrowDetails")
                        .HasForeignKey("BorrowRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BorrowRequest");
                });

            modelBuilder.Entity("Libary_asm.Models.BorrowRequest", b =>
                {
                    b.HasOne("Libary_asm.Models.User", "User")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Libary_asm.Models.User", b =>
                {
                    b.HasOne("Libary_asm.Models.BorrowRequest", "BorrowRequest")
                        .WithMany()
                        .HasForeignKey("BorrowRequestId1");

                    b.Navigation("BorrowRequest");
                });

            modelBuilder.Entity("Libary_asm.Models.Book", b =>
                {
                    b.Navigation("BorrowDetails");
                });

            modelBuilder.Entity("Libary_asm.Models.BorrowRequest", b =>
                {
                    b.Navigation("BorrowDetails");
                });

            modelBuilder.Entity("Libary_asm.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Libary_asm.Models.User", b =>
                {
                    b.Navigation("BorrowRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
